import pygame

pygame.init()

longueur = 800
largeur = 600

pygame.display.set_caption("Oratosh's world")

def accueil() :
    
    while True:
        screen.blit(255, 0, 0) #ici nous ajoutons une couleur au background
        
        MOUSE_POS = pygame.mouse.get_pos() #Nous vérifions la position de la souris + si on clique ou on parcourt seulement
        MENU_TEXT = get_font(100).render("Accueil", True, "#b68f40") #on fait appel à un font, on affiche le texte, True permet d'avoir un affichage plus esthétique
        MENU_POS = get_rect(center= (640, 100))
        
        BOUTON_JOUER = Button(image=pygame.image.load("assets/Play Rect.png"), pos= (640, 250),
                              text_input= "PLAY", font=get_font(75), base_color = "#d7fcd4", hovering_color="White")
        
        screen.blit(MENU_TEXT, MENU_POS)
        
        
